apiVersion: apps/v1
kind: Deployment

metadata:
  name: data-service-deployment
  namespace: poc
  labels:
    app: data

spec:
  replicas: 2
  
  # requirement of spec
  selector:
    matchLabels:
      app: data
  
  # requirement of spec
  template:
    metadata:
      labels:
        app: data
    spec:
      containers:
      
      - name: oauth2rs
        image: vhacr2.azurecr.io/oauth2rs:latest
        
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
              memory: "256Mi"
              cpu: "1000m"
        
        ports:
        - containerPort: 8080
          