apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiservice-deployment
  namespace: default
  labels:
    app: restservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: restservice
  template:
    metadata:
      labels:
        app: restservice
    spec:
      containers:
      - name: restservice
        image: vhacr1.azurecr.io/restservice:latest
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
              memory: "256Mi"
              cpu: "1000m"
        ports:
        - containerPort: 8080
          