apiVersion: v1
kind: Service
metadata:
  name: rest-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: rest-service
  ports:
    - protocol: TCP
      name: http
      port: 8080
      targetPort: 8080