apiVersion: v1
kind: Service

metadata:
  name: data-service
  namespace: poc

spec:
  type: ClusterIP
  selector:
    app: data
  ports:
    - protocol: TCP
      name: http
      port: 8080
      targetPort: 8080